[ru]
  title = "DoPoS"
  languageName = "Русский"
  weight = 1
  contentdir = "content/ru"
  logoText = "Docker-серверы"

[en]
  title = "DoPoS"
  languageName = "English"
  weight = 2
  contentdir = "content/en"
  logoText = "Docker Powered Servers"

