[[main]]
  identifier = "dcape"
  name = "DCAPE"
  url = "https://github.com/dopos/dcape"
  weight = 1

[[main]]
  identifier = "apps"
  name = "Приложения"
  url = "https://github.com/topics/dcape3-app"
  weight = 2

[[main]]
  identifier = "docs"
  name = "Документация"
  url = "dcape"
  weight = 3

[[main]]
  identifier = "updates"
  name = "Изменения"
  url = "dcape/changelog"
  weight = 4
