# custom app config
# overrides DCAPE/apps/drone/dcape-app/docker-compose.yml

version: '2'

services:
  app:
    environment:
      - VAR=value
    volumes:
      - ${APP_ROOT}/html:/usr/share/nginx/html:ro
