version: '2.1'

services:

  app:
    image: ${IMAGE}${IMAGE_VER}
    restart: always
    command: --minify -b http://${APP_SITE}
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.app.rule=Host(`${APP_SITE:?Must be set}`)
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}:/src
    networks:
      - lan

  dev:
    image: ${IMAGE}${IMAGE_VER}
    restart: always
    ports:
      - 8080:1313
    command: --debug server --bind 0.0.0.0 --appendPort=false -b http://${APP_SITE} --liveReloadPort=80 --disableFastRender
    labels:
      - traefik.enable=true
      - dcape.traefik.tag=${DCAPE_TAG}
      - traefik.http.routers.app.rule=Host(`${APP_SITE:?Must be set}`)
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}:/src
    networks:
      - lan

networks:
  lan:
    external:
      name: ${DCAPE_NET}
