---
kind: pipeline
type: docker
name: website

steps:

- name: deploy_local
  pull: never
  image: ${DCAPE_COMPOSE}
  commands:
  - . setup config
  - . setup root
  - make .drone-up
  volumes:
  - name: dockersock
    path: /var/run/docker.sock

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
